version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env

  work_app:
    build:
      context: .
    env_file:
      - .env
    container_name: work_app
    command: ["/project_dir/docker_instructions/app.sh"]
    ports:
      - 1111:8000
    depends_on:
      - db
    environment:
      DB_HOST: db


