"""update

Revision ID: 3fcfa71d6866
Revises: 8aada9489671
Create Date: 2023-10-29 14:30:05.150013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcfa71d6866'
down_revision: Union[str, None] = '8aada9489671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'record', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'user_id')
    # ### end Alembic commands ###
